### PR TITLE
Update Bank1.java

### PR DESCRIPTION
**Pull request by grpnpraveen**
1. )When the user enters to check balance and all, there is some disturbance that he need to enter the account number and pin again and again so that fixed
2. ) When user wants to change the credentials and suddenly if he refuses to ,then there is no option of going back so added the go back menu

### CODE REVIEW

**Comment by sishir2001** [comment]
Didn't get the first point.!!

**Comment by grpnpraveen** [comment]
While choosing his options it asking password and accountnumber many times

**Comment by sishir2001** [comment]
> Didn't get the first point.!!
The user just need to enter his credentials only once in the current version to!

**Comment by grpnpraveen** [comment]
NO NOT the CREDENTIALS ,I am talking about PASSWORD while selecting already have an account  in the current version it's asking again and again.Check it

**Comment by sishir2001** [comment]
why did u close the pull request
??

**Comment by sishir2001** [comment]
i want it to merge it.

**Pull request closed without merging**
